# Generated by Django 4.2.5 on 2023-09-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableconnect', '0002_course_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pack',
            field=models.CharField(default='TetraPak', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='recomend',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
            preserve_default=False,
        ),
    ]
